package:
  name: transpy
  version: '2020.9.1'

source:
  git_url: https://github.com/coderepocenter/TransPy
  git_rev: 2020.9.1

build:
  noarch: python
  number: 0

requirements:
  build:
    - git
  run:
    - python >=3.7
    - requests >=2.24.0
    - numpy >=1.19.0
    - ezrequest
    - pandas
    - geopandas
    - shapely
    - pyproj
about:
  summary: A collection of Python utilities assisting analytics and mapping related to transportation.